# What is the First Day of the Week?

Whether the Gregorian calendar shows Sunday or Monday as the first day of the week depends on where you live.

Do more countries start the week on Sunday or Monday? What about people? What about by continent?

The file `first-day-of-week.csv` shows the first day of the week for each territory. The file `population.csv` shows the population in the year 2020 for each territory in millions, and the file `four-regions.csv` specifies whether each territory is in asia, europe, africa, or the americas.

In [2]:
import pandas as pd
from pandas.conftest import axis_1

df = pd.read_csv('first-day-of-week.csv')
df.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

### Project Ideas

- How many territories show Friday, Saturday, Sunday, and Monday as the `first_day` of the week?

- How many people start the week on Friday, Saturday, Sunday, and Monday?
	- Hint: This will involve a `merge`.

- Which of the `four_regions` predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?
	- Hint: This will also involve a `merge`.

In [46]:
df_first_day = df.eval("first_day.isin(['fri','sat'])")

In [94]:
df_territory = df[df['first_day'].isin(['fri','sat'])]

In [95]:
df_territory

                territory alpha3 first_day   units paper  count     t_str
0             Afghanistan    AFG       sat  metric    A4      1       NaN
3                 Algeria    DZA       sat  metric    A4      1       NaN
18                Bahrain    BHR       sat  metric    A4      1       NaN
67               Djibouti    DJI       sat  metric    A4      1       NaN
71                  Egypt    EGY       sat  metric    A4      1       NaN
110                  Iran    IRN       sat  metric    A4      1       NaN
111                  Iraq    IRQ       sat  metric    A4      1       NaN
119                Jordan    JOR       sat  metric    A4      1       NaN
124                Kuwait    KWT       sat  metric    A4      1       NaN
131                 Libya    LBY       sat  metric    A4      1       NaN
139              Maldives    MDV       fri  metric    A4      1  Maldives
172                  Oman    OMN       sat  metric    A4      1       NaN
185                 Qatar    QAT       sat  metric    A4      1       NaN
218                 Sudan    SDN       sat  metric    A4      1       NaN
223                 Syria    SYR       sat  metric    A4      1       NaN
243  United Arab Emirates    ARE       sat  metric    A4      1       NaN

In [104]:
df_territory.loc[0].reset_index()

       index            0
0  territory  Afghanistan
1     alpha3          AFG
2  first_day          sat
3      units       metric
4      paper           A4
5      count            1
6      t_str          NaN

In [112]:
df_territory.iloc[0:10,2:]

    first_day   units paper  count t_str
0         sat  metric    A4      1   NaN
3         sat  metric    A4      1   NaN
18        sat  metric    A4      1   NaN
67        sat  metric    A4      1   NaN
71        sat  metric    A4      1   NaN
110       sat  metric    A4      1   NaN
111       sat  metric    A4      1   NaN
119       sat  metric    A4      1   NaN
124       sat  metric    A4      1   NaN
131       sat  metric    A4      1   NaN