In [197]:
import pandas as pd

df_territory = pd.read_csv("first-day-of-week.csv")

In [198]:
df_territory.head()

        territory alpha3 first_day   units paper
0     Afghanistan    AFG       sat  metric    A4
1   Aland Islands    ALA       mon  metric    A4
2         Albania    ALB       mon  metric    A4
3         Algeria    DZA       sat  metric    A4
4  American Samoa    ASM       sun  metric    A4

In [199]:
df_population = pd.read_csv("population.csv")

In [200]:
df_population.head()

  alpha3  population
0    AFG       39.07
1    ALB        2.87
2    DZA       44.04
3    AND        0.08
4    AGO       33.45

In [201]:
df_tp_merged = df_territory.merge(df_population, on="alpha3", how='left')

In [202]:
df_tp_merged

           territory alpha3 first_day   units paper  population
0        Afghanistan    AFG       sat  metric    A4       39.07
1      Aland Islands    ALA       mon  metric    A4         NaN
2            Albania    ALB       mon  metric    A4        2.87
3            Algeria    DZA       sat  metric    A4       44.04
4     American Samoa    ASM       sun  metric    A4         NaN
..               ...    ...       ...     ...   ...         ...
252  Wallis & Futuna    WLF       mon  metric    A4         NaN
253   Western Sahara    ESH       mon  metric    A4         NaN
254            Yemen    YEM       sun  metric    A4       36.13
255           Zambia    ZMB       mon  metric    A4       19.06
256         Zimbabwe    ZWE       sun  metric    A4       15.53

[257 rows x 6 columns]

In [203]:
df_regions = pd.read_csv('four-regions.csv')

In [204]:
df_regions.head()

  alpha3 four_regions
0    AUS         asia
1    BRN         asia
2    KHM         asia
3    CHN         asia
4    FJI         asia

In [205]:
final_df = df_tp_merged.merge(df_regions, on="alpha3", how='left')

In [206]:
final_df.columns

Index(['territory', 'alpha3', 'first_day', 'units', 'paper', 'population',
       'four_regions'],
      dtype='object')

In [207]:
col_map = {
    'territory': 'country',
    'four_regions': 'region'
}
final_df.rename(columns=col_map, inplace=True)

In [208]:
final_df.head()

          country alpha3 first_day   units paper  population  region
0     Afghanistan    AFG       sat  metric    A4       39.07    asia
1   Aland Islands    ALA       mon  metric    A4         NaN     NaN
2         Albania    ALB       mon  metric    A4        2.87  europe
3         Algeria    DZA       sat  metric    A4       44.04  africa
4  American Samoa    ASM       sun  metric    A4         NaN     NaN

In [209]:
final_df[final_df['population'].isna()]

                   country alpha3 first_day   units paper  population region
1            Aland Islands    ALA       mon  metric    A4         NaN    NaN
4           American Samoa    ASM       sun  metric    A4         NaN    NaN
7                 Anguilla    AIA       mon  metric    A4         NaN    NaN
8               Antarctica    ATA       mon  metric    A4         NaN    NaN
12                   Aruba    ABW       mon  metric    A4         NaN    NaN
..                     ...    ...       ...     ...   ...         ...    ...
239  U.S. Outlying Islands    UMI       sun  metric    A4         NaN    NaN
240    U.S. Virgin Islands    VIR       sun  metric    A4         NaN    NaN
249           Vatican City    VAT       mon  metric    A4         NaN    NaN
252        Wallis & Futuna    WLF       mon  metric    A4         NaN    NaN
253         Western Sahara    ESH       mon  metric    A4         NaN    NaN

[61 rows x 7 columns]

In [210]:
final_df.loc[final_df['population'].isna(), 'population'] = 0

In [211]:
region_mode = final_df['region'].mode()

In [212]:
final_df['region'].astype(str)

0        asia
1         nan
2      europe
3      africa
4         nan
        ...
252       nan
253       nan
254      asia
255    africa
256    africa
Name: region, Length: 257, dtype: object

In [213]:
final_df.loc[final_df['region'].isna(), 'region'] = region_mode

In [214]:
final_df.loc[final_df['region'].isna(), "region"] = 'america'

In [215]:
final_df

             country alpha3 first_day   units paper  population   region
0        Afghanistan    AFG       sat  metric    A4       39.07     asia
1      Aland Islands    ALA       mon  metric    A4        0.00  america
2            Albania    ALB       mon  metric    A4        2.87   europe
3            Algeria    DZA       sat  metric    A4       44.04   africa
4     American Samoa    ASM       sun  metric    A4        0.00  america
..               ...    ...       ...     ...   ...         ...      ...
252  Wallis & Futuna    WLF       mon  metric    A4        0.00  america
253   Western Sahara    ESH       mon  metric    A4        0.00  america
254            Yemen    YEM       sun  metric    A4       36.13     asia
255           Zambia    ZMB       mon  metric    A4       19.06   africa
256         Zimbabwe    ZWE       sun  metric    A4       15.53   africa

[257 rows x 7 columns]

In [216]:
final_df.loc[final_df['alpha3'].isna(), "alpha3"] = 'AME'

In [217]:
final_df.isna().sum()

country       0
alpha3        0
first_day     0
units         0
paper         0
population    0
region        0
dtype: int64

In [218]:
final_df.head()

          country alpha3 first_day   units paper  population   region
0     Afghanistan    AFG       sat  metric    A4       39.07     asia
1   Aland Islands    ALA       mon  metric    A4        0.00  america
2         Albania    ALB       mon  metric    A4        2.87   europe
3         Algeria    DZA       sat  metric    A4       44.04   africa
4  American Samoa    ASM       sun  metric    A4        0.00  america

- How many people start the week on Friday, Saturday, Sunday, and Monday?
	- Hint: This will involve a `merge`.

- Which of the `four_regions` predominantly start the week on Sunday? On Monday? Are there any regions that are more divided between Sunday and Monday?
	- Hint: This will also involve a `merge`.

In [219]:
df_eval = final_df[final_df['first_day'].isin(values=['fri','sat','sun','mon'])]

In [220]:
round(float(df_eval['population'].sum()),2)

7876.56

In [224]:
df_region_eval = final_df[final_df['first_day'].isin(values=['sun','mon'])]

In [232]:
new_df = df_region_eval[['region','first_day']]

In [233]:
new_df.shape

(241, 2)

In [236]:
new_df.groupby('first_day')['region'].count()

first_day
mon    186
sun     55
Name: region, dtype: int64