- What are the 10 largest islands in the tropics?

- What are the largest islands in each `region`?

- Create a line graph with `area` on the y-axis and `rank` on the x-axis. The data should be ordered by `rank`, from largest to smallest.

- What islands are composed of multiple countries?
	- Hint: try `countries.str.contains(",")`

In [39]:
import pandas as pd

df = pd.read_csv('largest-islands.csv')
df.head(5)

      region      island    area                countries    climate  rank
0     Africa  Madagascar  591896               Madagascar    tropics     4
1  Antarctic   Kerguelen    6200  Antarctic Lands, France  temperate    91
2       Asia       Sumba   11153                Indonesia    tropics    65
3       Asia      Hainan   34300                    China    tropics    37
4       Asia      Taiwan   36198                   Taiwan    tropics    36

- What are the 10 largest islands in the tropics?

In [43]:
df.query('climate == "tropics"').sort_values(by='area', ascending=False).head(10)

,region,island,area,countries,climate,rank
86,Oceania,New Guinea,821400,"Papua New Guinea, Indonesia",tropics,2
23,Asia,Borneo,755000,"Indonesia, Malaysia, Brunei",tropics,3
0,Africa,Madagascar,591896,Madagascar,tropics,4
28,Asia,Sumatra,480793,Indonesia,tropics,6
22,Asia,Sulawesi,188522,Indonesia,tropics,11
21,Asia,Java,129438,Indonesia,tropics,13
80,North America,Cuba,109884,Cuba,tropics,16
26,Asia,Luzon,104688,Philippines,tropics,17
14,Asia,Mindanao,94630,Philippines,tropics,19
73,North America,Hispaniola,76192,"Dominican Republic, Haiti",tropics,23

In [47]:
df.sort_values(by='rank' , ascending=True).head(10)

,region,island,area,countries,climate,rank
41,Europe,Greenland,2166086,Denmark,polar,1
86,Oceania,New Guinea,821400,"Papua New Guinea, Indonesia",tropics,2
23,Asia,Borneo,755000,"Indonesia, Malaysia, Brunei",tropics,3
0,Africa,Madagascar,591896,Madagascar,tropics,4
75,North America,Baffin Island,507451,Canada,polar,5
28,Asia,Sumatra,480793,Indonesia,tropics,6
27,Asia,Honshu,227898,Japan,temperate,7
69,North America,Victoria Island,217291,Canada,polar,8
43,Europe,Great Britain,209331,United Kingdom,temperate,9
83,North America,Ellesmere (Nunavut),196236,Canada,polar,10

In [49]:
df.query('rank <= 10').sort_values(by='area', ascending=False)

,region,island,area,countries,climate,rank
41,Europe,Greenland,2166086,Denmark,polar,1
86,Oceania,New Guinea,821400,"Papua New Guinea, Indonesia",tropics,2
23,Asia,Borneo,755000,"Indonesia, Malaysia, Brunei",tropics,3
0,Africa,Madagascar,591896,Madagascar,tropics,4
75,North America,Baffin Island,507451,Canada,polar,5
28,Asia,Sumatra,480793,Indonesia,tropics,6
27,Asia,Honshu,227898,Japan,temperate,7
69,North America,Victoria Island,217291,Canada,polar,8
43,Europe,Great Britain,209331,United Kingdom,temperate,9
83,North America,Ellesmere (Nunavut),196236,Canada,polar,10