In [1]:
import numpy as np
import pandas as pd
from requests.compat import numeric_types

df = pd.read_csv("../../../../data/movie_scores.csv")

missing values
in pandas missing value will be displayed as NaN for (not a Numeric) and (NaT)for (not a Timestamp)

In [2]:
np.nan

nan

In [3]:
type(pd.NA)

pandas._libs.missing.NAType

In [4]:
type(pd.NaT)

pandas._libs.tslibs.nattype.NaTType

In [5]:
pd.NA

In [6]:
pd.NaT

NaT

In [7]:
np.nan == np.nan

False

In [8]:
np.nan is np.nan

True

In [9]:
x = np.nan
y = x
id(x)

2370277794640

In [10]:
id(y)

2370277794640

In [11]:
x == y

False

check nan values with is operator and not with equality ==

In [12]:
my_var = np.nan
my_var is np.nan

True

In [13]:
df['first_name'] is np.nan

False

note that isnull() and isna() is moved to pd(pandas) directly to dataframe.

In [14]:
def check_if_nan(value):
    if pd.isnull(value) or pd.isna(value):
        return False
    return True

In [15]:
condition1 = df.apply(lambda df: check_if_nan(df['pre_movie_score']), axis=1)

In [16]:
condition2 = df.apply(lambda df: check_if_nan(df['first_name']), axis=1)

In [17]:
df[condition1]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

note that isnull() and isna() is moved to pd(pandas) directly to dataframe.

use ~ for not & for and and | for or

In [18]:
df[pd.notnull(df['pre_movie_score'])]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

working with no parenthesis for conditions for dataframe

In [19]:
df[pd.notnull(df['first_name']) & pd.notnull(df['pre_movie_score'])]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

drop all the rows as axis=0  where pre_movie_score col has NaN value

In [20]:
df.dropna(axis=0, subset=['pre_movie_score'])

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

drop if any value is missing in a column

In [21]:
df.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

set subset to column names where to look for dropping the 'NaN' valued rows

In [22]:
df.dropna(subset=['first_name','last_name','pre_movie_score','post_movie_score','age','sex'])

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

drop a row where all elements in a row are NaN, default axis = 0

In [23]:
df.dropna(how='all')

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

for our dataset is axis = 1 nothing has been dropped

In [24]:
df.dropna(how='all', axis=1)

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

thresh parameter checks if a row has how many non-NaN values if it is same or more than thresh value then it will be dropped

In [25]:
df.dropna(thresh=5)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

drop duplicates also get a subset plus has a keep option for keeping first or last record if found.

In [26]:
df.drop_duplicates(keep='last', subset=['first_name','last_name'])

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [27]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

### fillna

In [28]:
df['pre_movie_score'] = df['pre_movie_score'].ffill()
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              8.0               NaN
2       Hugh   Jackman  51.0    m              8.0               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [29]:
df['sex'] = df['sex'].fillna('M')

In [30]:
df['post_movie_score'] = df['post_movie_score'].fillna(df['post_movie_score'].mean())

In [31]:
df

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        NaN       NaN   NaN   M              8.0               9.0
2       Hugh   Jackman  51.0   m              8.0               9.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

Fill NA/NaN values by propagating the last valid observation to next valid.

In [32]:
df['first_name'] = df['first_name'].ffill()

In [33]:
df['age'] = df['age'].ffill()

In [34]:
df

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom       NaN  63.0   M              8.0               9.0
2       Hugh   Jackman  51.0   m              8.0               9.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

Fill NA/NaN values by using the next valid observation to fill the gap.

In [35]:
df['last_name'] = df['last_name'].bfill()

In [36]:
df

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom   Jackman  63.0   M              8.0               9.0
2       Hugh   Jackman  51.0   m              8.0               9.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [37]:
df['pre_movie_score'] = df['pre_movie_score'].replace(to_replace=0, value=df['pre_movie_score'].mean())

In [38]:
df

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom   Jackman  63.0   M              8.0               9.0
2       Hugh   Jackman  51.0   m              8.0               9.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [39]:
df.to_csv("../../../data/movie_scores_cleaned.csv", index=False, header=True, sep=",")

In [40]:
new_df = pd.read_csv("../../../../data/movie_scores_cleaned.csv")

In [41]:
new_df

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom   Jackman  63.0   M              8.0               9.0
2       Hugh   Jackman  51.0   m              8.0               9.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [42]:
new_df['pre_movie_score'].iloc[1:3]

1    8.0
2    8.0
Name: pre_movie_score, dtype: float64

In [43]:
new_df['pre_movie_score'].fillna(new_df['pre_movie_score'].mean())

0    8.0
1    8.0
2    8.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [44]:
new_df.fillna(new_df['pre_movie_score'].mean(), inplace=True)

In [45]:
new_df.to_csv("../../../data/movie_scores_cleaned.csv", index=False, header=True, sep=",")

In [46]:
new_df

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
1        Tom   Jackman  63.0   M              8.0               9.0
2       Hugh   Jackman  51.0   m              8.0               9.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [47]:
class_fare= {'exec': 100, 'first':np.nan, 'second':50 }

In [48]:
seri = pd.Series(class_fare)

In [49]:
seri

exec      100.0
first       NaN
second     50.0
dtype: float64

interpolate() is find the middle distance between before and after datapoint , essentially means a mean()

In [50]:
seri.interpolate()

exec      100.0
first      75.0
second     50.0
dtype: float64