In [13]:
import numpy as np
import pandas as pd
df = pd.read_csv('/data/tips.csv')

In [14]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [15]:
drop_cols = ['total_bill','smoker', 'Payment ID']
df.drop(drop_cols,axis=1,inplace=True)

In [16]:
df.head()

,tip,sex,day,time,size,price_per_person,Payer Name,CC Number
0,1.01,Female,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,1.66,Male,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,3.50,Male,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,3.31,Male,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,3.61,Female,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [21]:
df = df.rename(columns={'Payer Name' : 'payer_name' , 'CC Number' : 'cc_number',})

In [22]:
df.head()

,tip,sex,day,time,size,price_per_person,payer_name,cc_number
0,1.01,Female,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,1.66,Male,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,3.50,Male,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,3.31,Male,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,3.61,Female,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [23]:
df.to_csv(path_or_buf='/data/tips_new.csv', index=False)

In [24]:
df = pd.read_csv('/data/tips_new.csv')

In [25]:
df.head()

,tip,sex,day,time,size,price_per_person,payer_name,cc_number
0,1.01,Female,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,1.66,Male,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,3.50,Male,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,3.31,Male,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,3.61,Female,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221