In [8]:
import numpy as np
import pandas as pd

#### dataframes consists of columns and rows, and it internally a bunch/group of Series Objects with same shared index(s)

In [2]:
np.random.seed(101)
my_data = np.random.randint(0, 100, size=(4, 3))

In [3]:
my_data

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)

In [4]:
my_index = ['ind', 'usa', 'mex', 'bra']

In [5]:
my_cols_labels = ['q1', 'q2', 'q3']

#### data is enough

In [6]:
pd.DataFrame(data=my_data)

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

#### add column names, pandas assign default index(s) as numerical serial values

In [9]:
pd.DataFrame(data=my_data, columns=my_cols_labels)

   q1  q2  q3
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

#### just add labelled/named index remove cols

In [11]:
df = pd.DataFrame(data=my_data, index=my_index)
df

      0   1   2
ind  95  11  81
usa  70  63  87
mex  75   9  77
bra  40   4  63

#### add columns (they are just the labels here for columns) with data and index

In [12]:
df = pd.DataFrame(data=my_data, index=my_index, columns=my_cols_labels)
df

     q1  q2  q3
ind  95  11  81
usa  70  63  87
mex  75   9  77
bra  40   4  63

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, ind to bra
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   q1      4 non-null      int32
 1   q2      4 non-null      int32
 2   q3      4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes

In [137]:
df = pd.read_csv('../../../../data/tips.csv')

In [138]:
### basic Properties of DataFRame .............
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

#### columns and index
#### note that columns also treated as index at y-axis

In [142]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

#### at x-axis as it is a range it donates as RangeIndex()

In [143]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [13]:
## 50% is median
df.describe()

              q1         q2         q3
count   4.000000   4.000000   4.000000
mean   70.000000  21.750000  77.000000
std    22.730303  27.657127  10.198039
min    40.000000   4.000000  63.000000
25%    62.500000   7.750000  73.500000
50%    72.500000  10.000000  79.000000
75%    80.000000  24.000000  82.500000
max    95.000000  63.000000  87.000000

#### transpose using T/ transpose()

In [15]:
df.describe().T

    count   mean        std   min    25%   50%   75%   max
q1    4.0  70.00  22.730303  40.0  62.50  72.5  80.0  95.0
q2    4.0  21.75  27.657127   4.0   7.75  10.0  24.0  63.0
q3    4.0  77.00  10.198039  63.0  73.50  79.0  82.5  87.0