In [1]:

import numpy as np
import pandas as pd

df = pd.read_csv("../../../../data/mpg.csv")

In [2]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [3]:
df = df.select_dtypes(include=['number'])

In [11]:
mean_df = df.groupby(by= ['model_year','cylinders']).mean()

grab only 6/8 cylinders vehicles ... filter it earlier before group by

In [9]:
#mean_df = df[df['cylinders'].isin([6,8])].groupby(['model_year','cylinders']).mean()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         8          13.615385    344.846154  4228.384615     13.000000
73         6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         6          25.900000    196.500000  3145.500000     15.050000
81         6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         6          1.000000
           8          1.000000
71         6          1.000000
           8          1.000000
72         8          1.000000
73         6          1.250000
           8          1.000000
74         6          1.000000
           8          1.000000
75         6          1.000000
           8          1.000000
76         6          1.300000
           8          1.000000
77         6          1.400000
           8          1.000000
78         6          1.166667
           8          1.000000
79         6          1.000000
           8          1.000000
80         6          2.000000
81         6          1.714286
           8          1.000000
82         6          1.000000

In [12]:
#mean_df.swaplevel()

,,mpg,displacement,weight,acceleration,origin
cylinders,model_year,,,,,
4,70,25.285714,107.000000,2292.571429,16.000000,2.285714
6,70,20.500000,199.000000,2710.500000,15.500000,1.000000
8,70,14.111111,367.555556,3940.055556,11.194444,1.000000
4,71,27.461538,101.846154,2056.384615,16.961538,1.923077
6,71,18.000000,243.375000,3171.875000,14.750000,1.000000
8,71,13.428571,371.714286,4537.714286,12.214286,1.000000
3,72,19.000000,70.000000,2330.000000,13.500000,3.000000
4,72,23.428571,111.535714,2382.642857,17.214286,1.928571
8,72,13.615385,344.846154,4228.384615,13.000000,1.000000
3,73,18.000000,70.000000,2124.000000,13.500000,3.000000
4,73,22.727273,109.272727,2338.090909,17.136364,2.000000
6,73,19.000000,212.250000,2917.125000,15.687500,1.250000
8,73,13.200000,365.250000,4279.050000,12.250000,1.000000
4,74,27.800000,96.533333,2151.466667,16.400000,2.200000
6,74,17.857143,230.428571,3320.000000,16.857143,1.000000
8,74,14.200000,315.200000,4438.400000,14.700000,1.000000
4,75,25.250000,114.833333,2489.250000,15.833333,2.166667
6,75,17.583333,233.750000,3398.333333,17.708333,1.000000
8,75,15.666667,330.500000,4108.833333,13.166667,1.000000
4,76,26.766667,106.333333,2306.600000,16.866667,1.866667
6,76,20.000000,221.400000,3349.600000,17.000000,1.300000
8,76,14.666667,324.000000,4064.666667,13.222222,1.000000
3,77,21.500000,80.000000,2720.000000,13.500000,3.000000
4,77,29.107143,106.500000,2205.071429,16.064286,1.857143
6,77,19.500000,220.400000,3383.000000,16.900000,1.400000
8,77,16.000000,335.750000,4177.500000,13.662500,1.000000
4,78,29.576471,112.117647,2296.764706,16.282353,2.117647
5,78,20.300000,131.000000,2830.000000,15.900000,2.000000
6,78,19.066667,213.250000,3314.166667,16.391667,1.166667
8,78,19.050000,300.833333,3563.333333,13.266667,1.000000
4,79,31.525000,113.583333,2357.583333,15.991667,1.583333
5,79,25.400000,183.000000,3530.000000,20.100000,2.000000
6,79,22.950000,205.666667,3025.833333,15.433333,1.000000
8,79,18.630000,321.400000,3862.900000,15.400000,1.000000
3,80,23.700000,70.000000,2420.000000,12.500000,3.000000
4,80,34.612000,111.000000,2360.080000,17.144000,2.200000
5,80,36.400000,121.000000,2950.000000,19.900000,2.000000
6,80,25.900000,196.500000,3145.500000,15.050000,2.000000
4,81,32.814286,108.857143,2275.476190,16.466667,2.095238
6,81,23.428571,184.000000,3093.571429,15.442857,1.714286
8,81,26.600000,350.000000,3725.000000,19.000000,1.000000
4,82,32.071429,118.571429,2402.321429,16.703571,1.714286
6,82,28.333333,225.000000,2931.666667,16.033333,1.000000

In [16]:
mean_df.sort_index(level='model_year', ascending=False)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
82         6          28.333333    225.000000  2931.666667     16.033333
           4          32.071429    118.571429  2402.321429     16.703571
81         8          26.600000    350.000000  3725.000000     19.000000
           6          23.428571    184.000000  3093.571429     15.442857
           4          32.814286    108.857143  2275.476190     16.466667
80         6          25.900000    196.500000  3145.500000     15.050000
           5          36.400000    121.000000  2950.000000     19.900000
           4          34.612000    111.000000  2360.080000     17.144000
           3          23.700000     70.000000  2420.000000     12.500000
79         8          18.630000    321.400000  3862.900000     15.400000
           6          22.950000    205.666667  3025.833333     15.433333
           5          25.400000    183.000000  3530.000000     20.100000
           4          31.525000    113.583333  2357.583333     15.991667
78         8          19.050000    300.833333  3563.333333     13.266667
           6          19.066667    213.250000  3314.166667     16.391667
           5          20.300000    131.000000  2830.000000     15.900000
           4          29.576471    112.117647  2296.764706     16.282353
77         8          16.000000    335.750000  4177.500000     13.662500
           6          19.500000    220.400000  3383.000000     16.900000
           4          29.107143    106.500000  2205.071429     16.064286
           3          21.500000     80.000000  2720.000000     13.500000
76         8          14.666667    324.000000  4064.666667     13.222222
           6          20.000000    221.400000  3349.600000     17.000000
           4          26.766667    106.333333  2306.600000     16.866667
75         8          15.666667    330.500000  4108.833333     13.166667
           6          17.583333    233.750000  3398.333333     17.708333
           4          25.250000    114.833333  2489.250000     15.833333
74         8          14.200000    315.200000  4438.400000     14.700000
           6          17.857143    230.428571  3320.000000     16.857143
           4          27.800000     96.533333  2151.466667     16.400000
73         8          13.200000    365.250000  4279.050000     12.250000
           6          19.000000    212.250000  2917.125000     15.687500
           4          22.727273    109.272727  2338.090909     17.136364
           3          18.000000     70.000000  2124.000000     13.500000
72         8          13.615385    344.846154  4228.384615     13.000000
           4          23.428571    111.535714  2382.642857     17.214286
           3          19.000000     70.000000  2330.000000     13.500000
71         8          13.428571    371.714286  4537.714286     12.214286
           6          18.000000    243.375000  3171.875000     14.750000
           4          27.461538    101.846154  2056.384615     16.961538
70         8          14.111111    367.555556  3940.055556     11.194444
           6          20.500000    199.000000  2710.500000     15.500000
           4          25.285714    107.000000  2292.571429     16.000000

                        origin
model_year cylinders
82         6          1.000000
           4          1.714286
81         8          1.000000
           6          1.714286
           4          2.095238
80         6          2.000000
           5          2.000000
           4          2.200000
           3          3.000000
79         8          1.000000
           6          1.000000
           5          2.000000
           4          1.583333
78         8          1.000000
           6          1.166667
           5          2.000000
           4          2.117647
77         8          1.000000
           6          1.400000
           4          1.857143
           3          3.000000
76         8          1.000000
           6          1.300000
           4          1.866667
75         8          1.000000
           6          1.000000
           4          2.166667
74         8          1.000000
           6          1.000000
           4          2.200000
73         8          1.000000
           6          1.250000
           4          2.000000
           3          3.000000
72         8          1.000000
           4          1.928571
           3          3.000000
71         8          1.000000
           6          1.000000
           4          1.923077
70         8          1.000000
           6          1.000000
           4          2.285714