In [3]:
import numpy as np
import pandas as pd

In [4]:
data_one = {'A': ['A0', 'A1', 'A2', 'A3'],'B': ['B0', 'B1', 'B2', 'B3']}

In [5]:
data_two = {'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}

In [8]:
one = pd.DataFrame(data_one)
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [10]:
two = pd.DataFrame(data_two)
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

when concat use pd.conact() and pass those as a list '[]', and then if want to join them as columns then axis=1 or axis=0

In [11]:
pd.concat([one, two], axis=1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [13]:
# columns switched
pd.concat([two, one], axis=1)

    C   D   A   B
0  C0  D0  A0  B0
1  C1  D1  A1  B1
2  C2  D2  A2  B2
3  C3  D3  A3  B3

In [12]:
pd.concat([one, two], axis=0)

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [14]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [15]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [16]:
one.columns = two.columns

In [18]:
df = pd.concat([one,two], axis=0)

directly assigning to the index attribute , can be done using set_index()

In [24]:
## np.arange() also be used
df.index = range(len(df))

In [25]:
df

    C   D
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  C0  D0
5  C1  D1
6  C2  D2
7  C3  D3

In [27]:
registrations  = {
    "_id" : range(0,5),
    "names" :['mike','bob','tom','nikki','jonas'],
    'ages' : np.linspace(20,30, 5)
}

In [31]:
reg_df = pd.DataFrame(registrations)
reg_df

   _id  names  ages
0    0   mike  20.0
1    1    bob  22.5
2    2    tom  25.0
3    3  nikki  27.5
4    4  jonas  30.0

In [37]:
reg_df.set_index(keys=['_id'], inplace=True)
reg_df

     names  ages
_id
0     mike  20.0
1      bob  22.5
2      tom  25.0
3    nikki  27.5
4    jonas  30.0

In [58]:
logins  = {
    "_id" : range(0,5),
    #"names" :['michael','thomas','edison','george','samual'],
    #'ages' : np.linspace(45,55, 5),
     'salary' : np.linspace(10000,20000, 5),
     'phones' : np.arange(12345345,12345350)
}

In [59]:
log_df = pd.DataFrame(logins)
log_df

   _id   salary    phones
0    0  10000.0  12345345
1    1  12500.0  12345346
2    2  15000.0  12345347
3    3  17500.0  12345348
4    4  20000.0  12345349

In [60]:
log_df.set_index(keys=['_id'], inplace=True)

In [61]:
log_df

      salary    phones
_id
0    10000.0  12345345
1    12500.0  12345346
2    15000.0  12345347
3    17500.0  12345348
4    20000.0  12345349

In [63]:
merged_df = pd.merge(reg_df, log_df, on='_id', how='left')
merged_df

     names  ages   salary    phones
_id
0     mike  20.0  10000.0  12345345
1      bob  22.5  12500.0  12345346
2      tom  25.0  15000.0  12345347
3    nikki  27.5  17500.0  12345348
4    jonas  30.0  20000.0  12345349

In [109]:
import uuid
def get_uuid():
    yield str(uuid.uuid4())

def gen_uuids():
    uuids = []
    for i in range(5):
        uuid_str = get_uuid().__next__()
        uuids.append(uuid_str)

uuids

['75162ce3-9fa2-435c-bc76-2951825ba990',
 '10036a5c-afd0-4787-9fcc-2074b9b0d34d',
 '8fc7fce2-dcd6-4696-a314-c514006dbd2d',
 'd55f8968-166f-40f3-b25c-0b7f09e75836',
 'e2eca008-d5e2-476a-910f-29e5caffc1e0']

In [110]:
books = {
    '_id' : uuids,
    'names' :['python','java','ruby','rails','numpy'],
    'prices' : np.linspace(20,30,5)
}

In [111]:
books_df = pd.DataFrame(books)
books_df

                                    _id   names  prices
0  75162ce3-9fa2-435c-bc76-2951825ba990  python    20.0
1  10036a5c-afd0-4787-9fcc-2074b9b0d34d    java    22.5
2  8fc7fce2-dcd6-4696-a314-c514006dbd2d    ruby    25.0
3  d55f8968-166f-40f3-b25c-0b7f09e75836   rails    27.5
4  e2eca008-d5e2-476a-910f-29e5caffc1e0   numpy    30.0

In [116]:
authors = {
    '_id' : uuids,
    'names' :['','java','ruby','rails','numpy'],
    'authors' : ['tom','mike','bob','nikki','shawn'],
}

In [117]:
authors_df = pd.DataFrame(authors)
authors_df

                                    _id  names authors
0  75162ce3-9fa2-435c-bc76-2951825ba990            tom
1  10036a5c-afd0-4787-9fcc-2074b9b0d34d   java    mike
2  8fc7fce2-dcd6-4696-a314-c514006dbd2d   ruby     bob
3  d55f8968-166f-40f3-b25c-0b7f09e75836  rails   nikki
4  e2eca008-d5e2-476a-910f-29e5caffc1e0  numpy   shawn

merging will work only both data frames has matched values. if one of them doesn't have it then apply left or right join to catch having one ...

apply outer join if one value present and other doesn't ... but pandas will replace i other relative values as NaN in merged dataframe

inner...
when _id and names ==  _id and names

In [122]:
pd.merge(books_df, authors_df, on=['_id','names'], how='inner')

                                    _id  names  prices authors
0  10036a5c-afd0-4787-9fcc-2074b9b0d34d   java    22.5    mike
1  8fc7fce2-dcd6-4696-a314-c514006dbd2d   ruby    25.0     bob
2  d55f8968-166f-40f3-b25c-0b7f09e75836  rails    27.5   nikki
3  e2eca008-d5e2-476a-910f-29e5caffc1e0  numpy    30.0   shawn

left , include left

_id and names +==  _id and names

In [123]:
pd.merge(books_df, authors_df, on=['_id','names'], how='left')

                                    _id   names  prices authors
0  75162ce3-9fa2-435c-bc76-2951825ba990  python    20.0     NaN
1  10036a5c-afd0-4787-9fcc-2074b9b0d34d    java    22.5    mike
2  8fc7fce2-dcd6-4696-a314-c514006dbd2d    ruby    25.0     bob
3  d55f8968-166f-40f3-b25c-0b7f09e75836   rails    27.5   nikki
4  e2eca008-d5e2-476a-910f-29e5caffc1e0   numpy    30.0   shawn

right, include right

_id and names ==+  _id and names

In [124]:
pd.merge(books_df, authors_df, on=['_id','names'], how='right')

                                    _id  names  prices authors
0  75162ce3-9fa2-435c-bc76-2951825ba990            NaN     tom
1  10036a5c-afd0-4787-9fcc-2074b9b0d34d   java    22.5    mike
2  8fc7fce2-dcd6-4696-a314-c514006dbd2d   ruby    25.0     bob
3  d55f8968-166f-40f3-b25c-0b7f09e75836  rails    27.5   nikki
4  e2eca008-d5e2-476a-910f-29e5caffc1e0  numpy    30.0   shawn

both, include both no matter present, cartesian product

_id and names == _id and names

In [126]:
merged_outer = pd.merge(books_df, authors_df, on=['_id','names'], how='outer')

In [130]:
merged_outer[merged_outer['_id'] == '75162ce3-9fa2-435c-bc76-2951825ba990']

                                    _id   names  prices authors
1  75162ce3-9fa2-435c-bc76-2951825ba990             NaN     tom
2  75162ce3-9fa2-435c-bc76-2951825ba990  python    20.0     NaN