In [1]:
import numpy as np
import pandas as pd

In [2]:
age_grp = ['teen', 'adult', 'mature', 'old']
ages = [18, 35, 50, 75]

In [41]:
ages = pd.Series(data=ages, name='ages')
age_grp = pd.Series(data=age_grp, name='age_grp')

In [42]:
ages

0    18
1    35
2    50
3    75
Name: ages, dtype: int64

In [43]:
age_grp

0      teen
1     adult
2    mature
3       old
Name: age_grp, dtype: object

In [46]:
df1= pd.DataFrame(ages)
df1

   ages
0    18
1    35
2    50
3    75

In [47]:
df2= pd.DataFrame(age_grp)
df2

  age_grp
0    teen
1   adult
2  mature
3     old

In [52]:
pd.concat(join='inner', axis=1, objs=[df1, df2])

   ages age_grp
0    18    teen
1    35   adult
2    50  mature
3    75     old

In [55]:
joined_df = df1.join(df2, how='inner')

In [56]:
joined_df

   ages age_grp
0    18    teen
1    35   adult
2    50  mature
3    75     old