In [2]:
import numpy as np
import pandas as pd
from requests.compat import numeric_types

df = pd.read_csv('../../../../data/tips.csv')

In [3]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [5]:
def last_four(num):
    return str(num)[-4:]

In [6]:
last_four(1234567)

'4567'

In [7]:
df['last_four'] = df['CC Number'].apply(last_four)

In [8]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221

In [9]:
df['total_bill'].mean()

np.float64(19.78594262295082)

In [10]:
def yelp(price):
    if price < 10:
        return '$'
    elif 10 <= price <= 20:
        return '$$'
    else:
        return '$$$'

please note here that apply function call a function ref will return a single value which will be applied to a column value in a row.

It doesn't return any series.

In [11]:
df['yelp'] = df['total_bill'].apply(yelp)

In [12]:
df['yelp']

0       $$
1       $$
2      $$$
3      $$$
4      $$$
      ...
239    $$$
240    $$$
241    $$$
242     $$
243     $$
Name: yelp, Length: 244, dtype: object

In [13]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,$$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,$$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221,$$$

In [14]:
def quality_tip(total_bill, tip):
    if tip/total_bill > 0.18:
        return "OK"
    else:
        return "Other"

In [15]:
quality_tip(10.34,1.66)

'Other'

In [16]:
df[['total_bill','tip']].apply(lambda df:quality_tip(df['total_bill'],df['tip']), axis=1)

0      Other
1      Other
2      Other
3      Other
4      Other
       ...
239       OK
240    Other
241    Other
242    Other
243    Other
Length: 244, dtype: object

In [17]:
np.vectorize(quality_tip)(df['total_bill'], df['tip'])

array(['Other', 'Other', 'Other', 'Other', 'Other', 'OK', 'OK', 'Other',
       'Other', 'OK', 'Other', 'Other', 'Other', 'Other', 'OK', 'OK',
       'Other', 'OK', 'OK', 'Other', 'OK', 'Other', 'Other', 'OK',
       'Other', 'Other', 'Other', 'Other', 'OK', 'Other', 'Other',
       'Other', 'OK', 'Other', 'OK', 'Other', 'Other', 'OK', 'Other',
       'Other', 'Other', 'Other', 'OK', 'Other', 'OK', 'Other', 'OK',
       'OK', 'Other', 'Other', 'OK', 'OK', 'Other', 'Other', 'Other',
       'OK', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'OK', 'Other', 'Other', 'Other', 'OK', 'Other', 'Other',
       'Other', 'Other', 'Other', 'OK', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'OK', 'OK', 'Other', 'Other',
       'Other', 'Other', 'OK', 'OK', 'Other', 'Other', 'Other', 'Other',
       'OK', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'OK',
       'OK', 'Other', 'Other', 'OK', 'Other', 'OK', 'Other', 'OK', 'OK',
       'OK', 'Other', 'Other', 'Other', 'Other', 'OK', 'Other', 'Other',
       'Other', 'Other', 'OK', 'Other', 'Other', 'Other', 'OK', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'Other', 'OK', 'Other', 'Other', 'OK', 'OK',
       'OK', 'Other', 'OK', 'Other', 'Other', 'Other', 'Other', 'Other',
       'OK', 'Other', 'Other', 'Other', 'Other', 'Other', 'Other',
       'Other', 'Other', 'OK', 'Other', 'Other', 'OK', 'Other', 'Other',
       'Other', 'Other', 'Other', 'Other', 'Other', 'OK', 'OK', 'OK',
       'OK', 'Other', 'OK', 'Other', 'Other', 'Other', 'OK', 'Other',
       'Other', 'OK', 'Other', 'OK', 'Other', 'OK', 'Other', 'Other',
       'OK', 'Other', 'Other', 'OK', 'Other', 'Other', 'OK', 'OK', 'OK',
       'Other', 'Other', 'Other', 'OK', 'Other', 'Other', 'Other', 'OK',
       'OK', 'Other', 'Other', 'Other', 'Other', 'Other', 'OK', 'OK',
       'OK', 'OK', 'Other', 'Other', 'Other', 'OK', 'Other', 'OK', 'OK',
       'OK', 'OK', 'Other', 'Other', 'OK', 'Other', 'OK', 'Other',
       'Other', 'OK', 'OK', 'Other', 'OK', 'Other', 'Other', 'Other',
       'Other', 'OK', 'Other', 'Other', 'Other', 'Other'], dtype='<U5')

In [21]:
df.sort_values(by = ['tip','size'],ascending=False).head(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,8236,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,5212,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,9808,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139,0595,$$$
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025,8508,$$$
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059,9162,$$$
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374,1962,$$$
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677,4186,$$$
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657,2842,$$$
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003,9955,$$$

In [22]:
df['total_bill'].max()

np.float64(50.81)

In [23]:
df['total_bill'].idxmax()

170

In [24]:
df.iloc[170]

total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Payment ID                   Sat1954
last_four                       8236
yelp                             $$$
Name: 170, dtype: object

In [25]:
df['total_bill'].min()

np.float64(3.07)

In [29]:
df.iloc[df['total_bill'].idxmin()]

total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
last_four                       5267
yelp                               $
Name: 67, dtype: object

value_counts() works for string or categorical columns

In [30]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [31]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

unique values

In [32]:
df['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

no of unique values

In [33]:
df['day'].nunique()

4

replace and map works for array and dict resply

In [34]:
df['sex'].replace('Female','F')

0         F
1      Male
2      Male
3      Male
4         F
       ...
239    Male
240       F
241    Male
242    Male
243       F
Name: sex, Length: 244, dtype: object

for multiple

In [35]:
df['sex'].replace(['Female','Male'],['F','M'])

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

for multiple items in a column map is easier to work with than replace

In [37]:
my_map = {'Female':'F', 'Male':'M'}

In [38]:
df['sex'].map(my_map)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

check for duplicated() rows, returns True if exists

In [40]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [60]:
sample = pd.DataFrame([1,2,2,2], ['a','b','c','d'],columns=['series'])

In [57]:
sample

   series
a       1
b       2
c       2
d       2

In [61]:
sample.duplicated()

a    False
b    False
c     True
d     True
dtype: bool

In [62]:
sample.drop_duplicates()

   series
a       1
b       2

between values

In [71]:
df[df['total_bill'].astype(int).between(14,19,"left")]['total_bill'].head()

0     16.99
8     15.04
9     14.78
12    15.42
13    18.43
Name: total_bill, dtype: float64

In [77]:
df[df['tip'].ge(7)]['tip'].sort_values(ascending=False)

170    10.00
212     9.00
23      7.58
Name: tip, dtype: float64

In [87]:
df.select_dtypes(int).head()

   size         CC Number
0     2  3560325168603410
1     3  4478071379779230
2     3  6011812112971322
3     2  4676137647685994
4     4  4832732618637221

In [97]:
df.kurt(numeric_only=True, axis=0,)

total_bill          1.218484
tip                 3.648376
size                1.731700
price_per_person    1.823730
CC Number          -1.604941
dtype: float64

In [98]:
df.skew(axis=0,numeric_only=True)

total_bill          1.133213
tip                 1.465451
size                1.447882
price_per_person    1.201688
CC Number           0.122078
dtype: float64

In [100]:
df.query('total_bill > 10')['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 227, dtype: float64

similar to transpose

In [102]:
df.swapaxes(axis1=0,axis2=1)

C:\Users\vshan\AppData\Local\Temp\ipykernel_25228\2682562652.py:1: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  df.swapaxes(axis1=0,axis2=1)

,0,1,2,3,4,5,6,7,8,9,...,234,235,236,237,238,239,240,241,242,243
total_bill,16.99,10.34,21.01,23.68,24.59,25.29,8.77,26.88,15.04,14.78,...,15.53,10.07,12.6,32.83,35.83,29.03,27.18,22.67,17.82,18.78
tip,1.01,1.66,3.5,3.31,3.61,4.71,2.0,3.12,1.96,3.23,...,3.0,1.25,1.0,1.17,4.67,5.92,2.0,2.0,1.75,3.0
sex,Female,Male,Male,Male,Female,Male,Male,Male,Male,Male,...,Male,Male,Male,Male,Female,Male,Female,Male,Male,Female
smoker,No,No,No,No,No,No,No,No,No,No,...,Yes,No,Yes,Yes,No,No,Yes,Yes,No,No
day,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,Sun,...,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Sat,Thur
time,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,...,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner,Dinner
size,2,3,3,2,4,4,2,4,2,2,...,2,2,2,2,3,3,2,2,2,2
price_per_person,8.49,3.45,7.0,11.84,6.15,6.32,4.38,6.72,7.52,7.39,...,7.76,5.04,6.3,16.42,11.94,9.68,13.59,11.34,8.91,9.39
Payer Name,Christy Cunningham,Douglas Tucker,Travis Walters,Nathaniel Harris,Tonya Carter,Erik Smith,Kristopher Johnson,Robert Buck,Joseph Mcdonald,Jerome Abbott,...,Tracy Douglas,Sean Gonzalez,Matthew Myers,Thomas Brown,Kimberly Crane,Michael Avila,Monica Sanders,Keith Wong,Dennis Dixon,Michelle Hardin
CC Number,3560325168603410,4478071379779230,6011812112971322,4676137647685994,4832732618637221,213140353657882,2223727524230344,3514785077705092,3522866365840377,3532124519049786,...,4097938155941930,3534021246117605,3543676378973965,4284722681265508,676184013727,5296068606052842,3506806155565404,6011891618747196,4375220550950,3511451626698139
Payment ID,Sun2959,Sun4608,Sun4458,Sun5260,Sun2251,Sun9679,Sun5985,Sun8157,Sun6820,Sun3775,...,Sat7220,Sat4615,Sat5032,Sat2929,Sat9777,Sat2657,Sat1766,Sat3880,Sat17,Thur672
last_four,3410,9230,1322,5994,7221,7882,0344,5092,0377,9786,...,1930,7605,3965,5508,3727,2842,5404,7196,0950,8139
yelp,$$,$$,$$$,$$$,$$$,$$$,$,$$$,$$,$$,...,$$,$$,$$,$$$,$$$,$$$,$$$,$$$,$$,$$

In [104]:
df.corr(numeric_only=True)

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [108]:
df['total_bill'].abs()

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

subset or window calculations

In [115]:
df['total_bill'].rolling(window=3, min_periods=1).sum()

0      16.99
1      27.33
2      48.34
3      55.03
4      69.28
       ...
239    97.69
240    92.04
241    78.88
242    67.67
243    59.27
Name: total_bill, Length: 244, dtype: float64

getting specific rows of largest values , sort_values() and head(with number)

In [116]:
df['tip'].nlargest(2)

170    10.0
212     9.0
Name: tip, dtype: float64

In [117]:
df.nlargest(3, 'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,8236,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590,5212,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,9808,$$$

In [129]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,3410,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,9230,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,1322,$$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,5994,$$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,7221,$$$

In [134]:
df[['total_bill','Payer Name','size']].rank(axis=0,ascending=True)

     total_bill  Payer Name   size
0         113.0        41.0   82.5
1          25.5        59.0  179.5
2         162.5       234.0  179.5
3         179.0       181.0   82.5
4         187.0       231.0  217.0
..          ...         ...    ...
239       209.0       167.0  179.5
240       201.0       175.0   82.5
241       172.0       134.0   82.5
242       124.0        54.0   82.5
243       140.0       174.0   82.5

[244 rows x 3 columns]

get n smallest values

In [137]:
df[['tip','total_bill']].nsmallest(3, ['tip','total_bill'])

     tip  total_bill
67   1.0        3.07
92   1.0        5.75
111  1.0        7.25

replacement for nsmallest

In [139]:
df['tip'].sort_values(ascending=True).iloc[0:2]

92     1.0
111    1.0
Name: tip, dtype: float64

replacement for nlargest

In [143]:
df[['total_bill','tip']].sort_values('tip',ascending=False).iloc[0:2]

     total_bill   tip
170       50.81  10.0
212       48.33   9.0

sampling a dataframe values

In [153]:
# random 5 rows
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176,4664,$$$
14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,30016702287574,Sun3848,7574,$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954,8236,$$$
71,17.07,3.00,Female,No,Sat,Dinner,3,5.69,Teresa Fisher,5442222963796367,Sat3469,6367,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032,3965,$$

In [155]:
# random fraction percentage rows
df.sample(frac=0.1)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,last_four,yelp
169,10.63,2.00,Female,Yes,Sat,Dinner,2,5.32,Amy Hill,3536332481454019,Sat1788,4019,$$
151,13.13,2.00,Male,No,Sun,Dinner,2,6.56,Jason Arnold,3571825125296106,Sun2127,6106,$$
177,14.48,2.00,Male,Yes,Sun,Dinner,2,7.24,John Dudley,4565183162071073,Sun6203,1073,$$
164,17.51,3.00,Female,Yes,Sun,Dinner,2,8.76,Audrey Griffin,3500853929693258,Sun444,3258,$$
200,18.71,4.00,Male,Yes,Thur,Lunch,3,6.24,Jason Conrad,4581233003487,Thur6048,3487,$$
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374,1962,$$$
49,18.04,3.00,Male,No,Sun,Dinner,2,9.02,William Roth,6573923967142503,Sun9774,2503,$$
134,18.26,3.25,Female,No,Thur,Lunch,2,9.13,Karen Rodriguez,4952604748911,Thur75,8911,$$
127,14.52,2.00,Female,No,Thur,Lunch,2,7.26,Jessica Simmons,213102478792200,Thur1512,2200,$$
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4387671121369212,Sun3279,9212,$
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4590982568244,Sat7320,8244,$$$
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5448125351489749,Sat9618,9749,$$$
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176,4664,$$$
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,Richard Stevens,3560193117506187,Sun1821,6187,$$$
136,10.33,2.00,Female,No,Thur,Lunch,2,5.16,Donna Kelly,180048553626376,Thur1393,6376,$$
57,26.41,1.50,Female,No,Sat,Dinner,2,13.20,Melody Simon,4745394421258160,Sat8980,8160,$$$
66,16.45,2.47,Female,No,Sat,Dinner,2,8.22,Rachel Vaughn,3569262692675583,Sat4750,5583,$$
195,7.56,1.44,Male,No,Thur,Lunch,2,3.78,Michael White,4865390263095532,Thur697,5532,$
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239,9808,$$$
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677,4186,$$$
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672,8139,$$
186,20.90,3.50,Female,Yes,Sun,Dinner,3,6.97,Heidi Atkinson,4422858423131187,Sun4254,1187,$$$
51,10.29,2.60,Female,No,Sun,Dinner,2,5.14,Jessica Ibarra,4999759463713,Sun4474,3713,$$
61,13.81,2.00,Male,Yes,Sat,Dinner,2,6.90,Ryan Hernandez,4766834726806,Sat3030,6806,$$

other remaining functions check help or pandas docs